spring.application.name=Banfico-Training program
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=require&channelBinding=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${KEYCLOAK_JWK_URI}

keycloak.admin.url=${KEYCLOAK_ADMIN_URL}
keycloak.admin.username=${KEYCLOAK_ADMIN_USERNAME}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD}
keycloak.admin.realm=bankapp

spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.keepalive-time=0
